Задание 1

Создайте класс с main(), который закидывает (throws) объект класса Exception внутрь try-блока.
Задайте конструктору исключения (Exception) аргумент типа String.
Поймайте (catch) исключение внутри catch-блока и выведитe String argument.
Добавьте finally-блок и выведите сообщение в доказательство того, что он вызывался.

Задание 2

Создайте свой собственный класс исключений, используя ключевое слово extends.
Напишите конструктор для этого класса, который получает аргумент типа String и хранит его внутри объекта как ссылку (reference) на String.
Написать метод, который выводит хранимую строку.
Создать try-catch-блоки, чтобы поупражняться на новом исключении.

Задание 3

Определите ссылку (reference) на объект и инициализируйте ее как null. Попробуйте вызвать метод через эту ссылку.
Потом оберните этот код в try-catch-блок, чтобы поймать исключение.

Задание 4

Создайте класс с двумя методами f() и g().
В g() киньте (throw) исключение нового типа, который вы определили.
В f() вызовите g(), поймайте его исключение и в блоке catch киньте другое исключение (другого типа, который вы определили).
Протестируйте свой код в main().

Задание 5

Создайте три новых типа исключений. Напишите класс с методом, который будет кидать все три из них.
В main() вызовите этот метод, но используйте только один catch-блок который будет ловить все три типа исключений.